### ISSUE TITLE
Embed static HTML documentation

### ISSUE THREAD

**Issue by TuanDQ-Tuev-Sued** [EclipseFdn/openpass.eclipse.org#100]
Currently we are hosting a developer, a user documentation and an installation guide at two places: 
1. at the openPASS webpage https://openpass.eclipse.org/resources/#documentation and 
2. at the sim@openpass repository under https://gitlab.eclipse.org/eclipse/simopenpass/simopenpass/-/tree/master/sim/doc. 

Those documents are .chm-files which we want to change into a more beautiful documentation. For that reason, we have written a new documentation with sphinx. The documentation is a static HTML page.

Unfortunately, a quick attempt to link the HTML here https://www.eclipse.org/simopenpass/ did not succeed. It needs deeper knowledge in PHP, Solstice (https://www.eclipse.org/eclipse.org-common/themes/solstice/docs/) and/or Phoenix (https://wiki.eclipse.org/Using_Phoenix)...

Attached is an exemplary HTML documentation.
[html.zip](https://github.com/EclipseFdn/openpass.eclipse.org/files/6654374/html.zip)

Is there an easy way to embed the HTML file within the webpage?

**Comment by chrisguindon** [comment]
@TuanDQ-Tuev-Sued,

We have an example here how you can leverage Jenkins to commit content to your website repository each time you make a commit: https://github.com/EclipseFdn/hugo-eclipsefdn-website-boilerplate/blob/main/Jenkinsfile

However, I am not familiar with sphinx.

**Comment by chrisguindon** [comment]
However, a simpler aproach would be to simply commit the content of your zip file in a sub direcvotry of this repository such as /docs: https://git.eclipse.org/r/admin/repos/www.eclipse.org/simopenpass

That will allow users to access the content under https://www.eclipse.org/simopenpass/docs

**Comment by TuanDQ-Tuev-Sued** [comment]
Thanks again! This solves the issue.
