### ISSUE TITLE
Migrate website source repository to Eclipse Gitlab

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/openpass.eclipse.org#105]
Over the last few months, we've been busy migrating some of our websites to Eclipse Gitlab:
https://gitlab.eclipse.org/eclipsefdn/it/websites

Today, I would like to recommend that we migrate this website repository under https://gitlab.eclipse.org/eclipsefdn/it/websites

This move makes it easier for foundation staff to collaborate and manage priorities since we can review issues by group https://gitlab.eclipse.org/groups/eclipsefdn/it/websites/-/issues

Triage is a bit more time-consuming on Github since we need to manually visit the issue queue of each project.

@TuanDQ-Tuev-Sued  Do you have any issues with us moving this repository? Also, if you agree, do you need some time to communicate this change with the rest of the WG before we do the move?

I can help with sending an email! Let me know if you have any questions!

Thanks!

**Comment by TuanDQ-Tuev-Sued** [comment]
@chrisguindon To understand the transition correct: The management of issues is being moved to GitLab but the hosting of the webpage (now: https://github.com/EclipseFdn/openpass.eclipse.org) isn't being touched, right?

**Comment by TuanDQ-Tuev-Sued** [comment]
I agree to the migration.

**Comment by chrisguindon** [comment]
Thanks, @TuanDQ-Tuev-Sued! I am starting the migration this morning! I will report back once it's done!

**Comment by chrisguindon** [comment]
The migration has been done! 

The new home for the source code of the openpass.eclipse.org website is now on Gitlab:
https://gitlab.eclipse.org/eclipsefdn/it/websites/openpass.eclipse.org

Thanks @TuanDQ-Tuev-Sued
