### ISSUE TITLE
ability to order the list of membership level 

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/openpass.eclipse.org#20]
As discussed in our previous meeting, we need to ability to change the order of the membership level on this page:
https://eclipsefdn-openpass.netlify.com/membership/

I created an issue in our base theme to support this feature:
https://github.com/EclipseFdn/hugo-solstice-theme/issues/115

If this is an urgent issue to fix, I would recommend hardcoding the membership level in the shortcodes file:

https://github.com/EclipseFdn/openpass.eclipse.org/blob/master/layouts/shortcodes/members_list.html#L17

**Comment by TuanDQ-Tuev-Sued** [comment]
The members are now in alphabetical order. I am closing this issue
