### ISSUE TITLE
Refresh website content

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/openpass.eclipse.org#27]
Please find attached the new content for the openPASS website:

[website-content.zip](https://github.com/EclipseFdn/openpass.eclipse.org/files/4656880/website-content.zip)

I would like to get this done by June 3rd, 2020!

**Comment by chrisguindon** [comment]
@autumnfound We are responsible for implementing these changes. I am adding @TuanDQ-Tuev-Sued to help him follow us with the progress of this task!

@TuanDQ-Tuev-Suedis the product manager for openPass and he provided the content for the website.

**Comment by autumnfound** [comment]
## Startpage:
"Tutorial: How to configure a simulation with openPASS" is not recommended as a menu item title. This is far too long, and will not render well. I would recommend something along the lines of "Tutorials", "How-to Configure", or "Configure a Simulation" (which is still long but is much better).

## Target Objectives:
Do we have the images in the following screenshot and the rights to them? I'll need them to create those tiles.
![image](https://user-images.githubusercontent.com/23018241/82450807-2c1d6400-9a7b-11ea-87fa-d276ab45f6d5.png)

## Resources:
Did you want these resources as separate pages somewhat like [IoT](https://iot.eclipse.org/community/resources/) or on one page like [Jakarta](https://jakarta.ee/resources/)?

## Contact:
We can't guarantee that contact details will always be side-by-side, as the space required may not always be available (like on smaller devices or shrunk web browser windows). We can make them go from 3 in a row, and gracefully go down to 1 per row on small screens. Does that work?

**Comment by chrisguindon** [comment]
@TuanDQ-Tuev-Sued feel free to step-in!

> ## Startpage:
> "Tutorial: How to configure a simulation with openPASS" is not recommended as a menu item title. This is far too long, and will not render well. I would recommend something along the lines of "Tutorials", "How-to Configure", or "Configure a Simulation" (which is still long but is much better).

I agree that we should use less text for a menu item. I like Tutorials" or something like"Getting Started"?

> 
> ## Target Objectives:
> Do we have the images in the following screenshot and the rights to them? I'll need them to create those tiles.
> ![image](https://user-images.githubusercontent.com/23018241/82450807-2c1d6400-9a7b-11ea-87fa-d276ab45f6d5.png)

I defer to @TuanDQ-Tuev-Sued 

> ## Resources:
> Did you want these resources as separate pages somewhat like [IoT](https://iot.eclipse.org/community/resources/) or on one page like [Jakarta](https://jakarta.ee/resources/)?


One page? I thinking that we should simple it simple for now since we don't have a lot of content for this page.

> ## Contact:
> We can't guarantee that contact details will always be side-by-side, as the space required may not always be available (like on smaller devices or shrunk web browser windows). We can make them go from 3 in a row, and gracefully go down to 1 per row on small screens. Does that work?

+1

**Comment by TuanDQ-Tuev-Sued** [comment]
> @TuanDQ-Tuev-Sued feel free to step-in!
> 
> > ## Startpage:
> > "Tutorial: How to configure a simulation with openPASS" is not recommended as a menu item title. This is far too long, and will not render well. I would recommend something along the lines of "Tutorials", "How-to Configure", or "Configure a Simulation" (which is still long but is much better).
> 
> I agree that we should use less text for a menu item. I like Tutorials" or something like"Getting Started"?
> 
Good point! The title is indeed way too long. Please rename it to "Tutorial"
> > ## Target Objectives:
> > Do we have the images in the following screenshot and the rights to them? I'll need them to create those tiles.
> > ![image](https://user-images.githubusercontent.com/23018241/82450807-2c1d6400-9a7b-11ea-87fa-d276ab45f6d5.png)
> 
> I defer to @TuanDQ-Tuev-Sued
> 
Yes, we have the rights to publish them!

Attached you can find the images.
![traffic_simulation](https://user-images.githubusercontent.com/54616555/82457196-728fb480-9ab5-11ea-9d65-56a9b5d5bb91.jpg)
![gauss](https://user-images.githubusercontent.com/54616555/82457199-73284b00-9ab5-11ea-8ac8-0cd7e1ed8bb5.jpg)
![standardized_interfaces](https://user-images.githubusercontent.com/54616555/82457202-73c0e180-9ab5-11ea-81c7-cba3eb543685.jpg)
![reproducibility](https://user-images.githubusercontent.com/54616555/82457201-73284b00-9ab5-11ea-9624-23952f07ade3.jpg)

> > ## Resources:
> > Did you want these resources as separate pages somewhat like [IoT](https://iot.eclipse.org/community/resources/) or on one page like [Jakarta](https://jakarta.ee/resources/)?
> 
> 1 page for now:
> 
> I thinking that we should keep this simple for now since we don't have a lot of content for this page.
> 
Yes, you can keep it simple by making one page.
> > ## Contact:
> > We can't guarantee that contact details will always be side-by-side, as the space required may not always be available (like on smaller devices or shrunk web browser windows). We can make them go from 3 in a row, and gracefully go down to 1 per row on small screens. Does that work?
> 
> +1

Yes, that would work!

**Comment by TuanDQ-Tuev-Sued** [comment]
Under chapter 2 we want a link to open the following presentation slides (I forgot to send them to you): 
[20200304_openPASS_at_a_glance_final_v9.pdf](https://github.com/EclipseFdn/openpass.eclipse.org/files/4657621/20200304_openPASS_at_a_glance_final_v9.pdf)

**Comment by autumnfound** [comment]
There seems to be a lot of graphics used in the content. Could I have copies of those sent over? I wouldn't be able to get good resolution versions from the documents sent over likely.

**Comment by TuanDQ-Tuev-Sued** [comment]
Sure, attached you can find the graphics. I hope they fit your requirements.

![platform_concept](https://user-images.githubusercontent.com/54616555/82794095-38863000-9e72-11ea-97e8-e752caacb3a5.jpg)
![standards](https://user-images.githubusercontent.com/54616555/82795445-518fe080-9e74-11ea-9bd7-972e10187855.jpg)
![simulation_platform](https://user-images.githubusercontent.com/54616555/82795442-50f74a00-9e74-11ea-9f0a-6e188d16c250.jpg)
![core_modules](https://user-images.githubusercontent.com/54616555/82795440-50f74a00-9e74-11ea-9682-88189960b294.jpg)
![agent_components](https://user-images.githubusercontent.com/54616555/82795439-50f74a00-9e74-11ea-9dc5-9b5e671fd6e7.jpg)
![simulation_process](https://user-images.githubusercontent.com/54616555/82795443-518fe080-9e74-11ea-80bf-86f50e3f0e07.jpg)
![timeline](https://user-images.githubusercontent.com/54616555/82795435-505eb380-9e74-11ea-9da6-9683f4a78698.jpg)

**Comment by TuanDQ-Tuev-Sued** [comment]
@autumnfound  @chrisguindon The openPASS WG has developed an installer for an easy and self-explanatory installation for Windows. All the licenses in the installer can be used as binaries (conform with the third party dependencies). We would add an about dialog to mention which licenses are used. Does it conform with the EF rules to put that installer on to webpage?

**Comment by autumnfound** [comment]
Here is a preview of the current progress: https://deploy-preview-28--eclipsefdn-openpass.netlify.app/

The big takeaway is that there is still some content/links missing on the resources page, and a fix for a wider issue still needs to be made for the homepage in the base theme. That is currently in progress and should be done in the next couple of days.

**Comment by TuanDQ-Tuev-Sued** [comment]
Pdf to the installation guide:
[OSI World Setup Guide.pdf](https://github.com/EclipseFdn/openpass.eclipse.org/files/4680978/OSI.World.Setup.Guide.pdf)

Tutorial:
[Tutorial_openPass_GUI.pdf](https://github.com/EclipseFdn/openpass.eclipse.org/files/4680980/Tutorial_openPass_GUI.pdf)

Documentation:
The documentations are in a .chm-format. I can not upload a .chm-file. Is there any other way to provide that document?

**Comment by autumnfound** [comment]
You can zip files and upload the zip to attach those files

**Comment by TuanDQ-Tuev-Sued** [comment]
[Documentation.zip](https://github.com/EclipseFdn/openpass.eclipse.org/files/4682701/Documentation.zip)
