### ISSUE TITLE
Change Request Webpage Layout

### ISSUE THREAD

**Issue by TuanDQ-Tuev-Sued** [EclipseFdn/openpass.eclipse.org#29]
Hi all,

the first draft for the webpage looks already really good! Still, I want to make some suggestions.

1. On the very first page no text appears under "Events, Activities and News". Please add the following: "The openPASS working group organizes itself into a Steering Committee and an Architecture Committee. Every 2 weeks either an SC meeting or an AC meeting takes place in alternating order. In the sense of an open source project every meeting is being logged and freely available to public. The meeting minutes can be found on Eclipsepedia." Then add a button "Eclipsepedia" with a link to this webpage https://wiki.eclipse.org/OpenPASS-WG
2. Please organize the "Working Group" tab as "Resources" such that all the subtabs are listed on one site as in "Resources".

Thanks in advance!

Best regards
Tuan

**Comment by chrisguindon** [comment]
Thanks for the issue @TuanDQ-Tuev-Sued! We will work on getting this done!

**Comment by TuanDQ-Tuev-Sued** [comment]
> Hi all,
> 
> the first draft for the webpage looks already really good! Still, I want to make some suggestions.
> 
> 1. On the very first page no text appears under "Events, Activities and News". Please add the following: "The openPASS working group organizes itself into a Steering Committee and an Architecture Committee. Every 2 weeks either an SC meeting or an AC meeting takes place in alternating order. In the sense of an open source project every meeting is being logged and freely available to public. The meeting minutes can be found on Eclipsepedia." Then add a button "Eclipsepedia" with a link to this webpage https://wiki.eclipse.org/OpenPASS-WG
> 2. Please organize the "Working Group" tab as "Resources" such that all the subtabs are listed on one site as in "Resources".
> 
> Thanks in advance!
> 
> Best regards
> Tuan

1. I have rewritten the content but still the text is not showing on the title page --> Still open to do. I have added a button with a link to the openPASS Eclipsepedia which is working, see PR https://github.com/EclipseFdn/openpass.eclipse.org/pull/31, this is done.
2. is done with PR https://github.com/EclipseFdn/openpass.eclipse.org/pull/30, thank you :)
