### ISSUE TITLE
Include "Members" into the "Working Group" tab

### ISSUE THREAD

**Issue by TuanDQ-Tuev-Sued** [EclipseFdn/openpass.eclipse.org#34]
Hi all,

when clicking on "Members" a seperate site is being opened. Please include the list of members onto the "Working Group" page between Timeline and Governance such that all information is listed under each other.

Best regards
Tuan

**Comment by autumnfound** [comment]
What do you mean for opening a separate site I've tested and it opens the expected subpage for listing members? Can you expand on what you're expecting for the new Members section? Did you want a simple list of members w/ links?

**Comment by TuanDQ-Tuev-Sued** [comment]
Thanks for the feedback!

Until now each section "Scope, Timeline, Governance, Members Committee" in "Working Group" is listed on one page, except "Members". When clicking on "Members" a subpage is being opened as you stated it correctly.

Is it possible to list the sections on one page without a subpage being opened when clicking on "Members". So, I want basically a list of members between "Timeline" and "Governance".

**Comment by autumnfound** [comment]
Do you want a basic text list, or the form you can see on the subpage?

**Comment by TuanDQ-Tuev-Sued** [comment]
I want the form we can see on the subpage without the left overview of the membership kinds. So as a title please keep "Driver", "Service Provider" and "User" in that blue box with the white font. Under each title list the companies as it is now in the subpage.

![image](https://user-images.githubusercontent.com/54616555/84134078-5645be80-aa48-11ea-812f-0551796f9813.png)

I hope that helps.
