### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by TuanDQ-Tuev-Sued** [EclipseFdn/openpass.eclipse.org#40]
There is a search button on the menu which apparently is just using Google. Is it possible to replace that in a webpage search? For example if I want to search the glossary of openPASS, I just type it in the search field and it suggests me the page on our webpage with the glossary? If this is not possible, just delete the loupe symbol.
![image](https://user-images.githubusercontent.com/54616555/84027770-d2300000-a98f-11ea-86e3-34012529f36f.png)

**Comment by chrisguindon** [comment]
This is designed as a search tool for all our websites. 

+1 for hiding the search icon for openpass.eclipse.org
