### ISSUE TITLE
Underline each URL

### ISSUE THREAD

**Issue by TuanDQ-Tuev-Sued** [EclipseFdn/openpass.eclipse.org#59]
To highlight an URL please add an underline. For now, the URLs are quite difficult to find and easy to oversee. You can only see the URL when you hover the mouse over it.

**Comment by chrisguindon** [comment]
I agree that the links are very hard to notice right now!

@TuanDQ-Tuev-Sued Would you prefer that we use a different color instead of adding an underline to each link?

I think the site would look nicer if we chose a better color instead of the underline!

**Comment by TuanDQ-Tuev-Sued** [comment]
@chrisguindon @autumnfound Ok, if you think this looks better so let's try it out! I think some dark blueish will do it but I am open to any color.
