### ISSUE TITLE
Image appearance on Architecture page

### ISSUE THREAD

**Issue by ArunDas1** [EclipseFdn/openpass.eclipse.org#66]
The images on the "Architecture" page under "Top-level Architecture" are optically not consistent with all other images on the web page and look old-fashioned. We have invested a lot of effort in beautifying the slide set and therefore all other images on the web page. Please make sure, that the appearance of the three mentioned images complies with the rest of the web page (i.e. use same colors, font styles, box styles).

Also these three images are the only ones that contain a copyright footer. I would suggest we do it uniformly for all images. Please check if this is needed. Maybe one disclaimer for the whole web page is enough as all images should have copyright by the members of our WG. 

@TuanDQ-Tuev-Sued: Again, this is probably something for you, right?

**Comment by TuanDQ-Tuev-Sued** [comment]
@ArunDas1 We will remove the copyright footer of those images. There are legal policies in the footer of the site. Therefore, I think that we do not need any copyright disclaimers.

The rest is work in progress.
