### ISSUE TITLE
Adding reference to DIN SAE SPEC 91381

### ISSUE THREAD

**Issue by TuanDQ-Tuev-Sued** [EclipseFdn/openpass.eclipse.org#81]
Adding the following text in the beginning of the glossary. 

As a reference for the used terms on the wepage the DIN SAE SPEC 91381 is being used. The standard consists of terms and definitions related to testing of automated vehicle. The document can be downloaded free of charge [here](https://www.beuth.de/de/technische-regel/din-sae-spec-91381/307106071).

**Comment by MaximilianKrausTuevSued** [comment]
done with pull request #82
