### ISSUE TITLE
No display of documentations

### ISSUE THREAD

**Issue by TuanDQ-Tuev-Sued** [EclipseFdn/openpass.eclipse.org#86]
When downloading the documentations under resources no content is displayed. The documentations are downloadable but the text is not shown. The docus can be downloaded here: https://openpass.eclipse.org/resources/#documentation.

1. Go to https://openpass.eclipse.org/resources/#documentation
2. Click on "documentation to openPASS" or "documentation to openPASS GUI".
3. Open the .chm-file and no text will be shown.

left expected behavior, right current behavior
![image](https://user-images.githubusercontent.com/54616555/89535288-84504080-d7f6-11ea-8965-55b5358a3cf7.png)

**Comment by autumnfound** [comment]
The issue with this is likely to do with the file sent over or how its opened. We just host the file for consumption. This likely has to do with the export or the file that is currently hosted. Replacing this file is likely how this will be resolved

**Comment by TuanDQ-Tuev-Sued** [comment]
@autumnfound Replacing this file does not solve the issue. I have tried it once before. Can it be that the system does not host .chm-files correctly?

**Comment by autumnfound** [comment]
`.chm` files are binary bins, so they should be written as is when committing. I'm unable to validate the file natively using the Windows CHM viewer as I use Linux. Installing an application I'm able to open both documents, both in the source repository, and downloaded raw from the website:
![image](https://user-images.githubusercontent.com/23018241/89795836-e1017300-daf6-11ea-9575-b7ea54c2e92d.png)

**Comment by TuanDQ-Tuev-Sued** [comment]
Thanks for the feedback. I have installed another viewer and now it works. Apparently it's an chm-viewer issue. Thanks for the help again!
